In [1]:
import numpy as np

In [2]:
python_list = [1, 2, 3]
numpy_array = np.array([1, 2, 3])

print(python_list * 2)   # Output: [1, 2, 3, 1, 2, 3]
print(numpy_array * 2)   # Output: [2, 4, 6]

temp_list = [32, 45, 28, 30]
temp_array = np.array(temp_list)

print(temp_array + 5)

[1, 2, 3, 1, 2, 3]
[2 4 6]
[37 50 33 35]


## 1 - How to create a numpy array

In [6]:
print(np.array([1, 2, 3]))      # Create a 1D array
print(np.zeros((2, 3)))         # Create a 2D array of zeros with shape (2, 3)
print(np.ones((2, 3)))          # Create a 2D array of ones with shape (2, 3)
print(np.arange(0, 10, 2))      # Create a 1D array with values from 0 to 10 (exclusive - không bao gồm) with a step of 2
print(np.linspace(0, 1, 7))     # Creaet a 1D array with 7 evenly spaced values between 0 and 1 (inclusive - bao gồm)

[1 2 3]
[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[0 2 4 6 8]
[0.         0.16666667 0.33333333 0.5        0.66666667 0.83333333
 1.        ]


`arange` and `linspace`
>- `arange` tạo dãy theo bước nhảy
>- `linspace` tạo dãy theo số lượng điểm, mặc định gồm 2 đầu mút

## 2 - Attribute of numpy array

In [ ]:
a = np.array([
    [1, 2, 3],
    [4, 5, 6]
])

print(a.ndim)       # The number of dimensions of the array
print(a.shape)      # The s hape of the array (number of rows, number of columns)
print(a.size)       # The total number of elements in the array
print(a.dtype)      # The data type of the elements in the array

2
(2, 3)
6
int64
