In [ ]:
import cv2
import numpy as np

image = cv2.imread('FakeBackground.png', 1)
print(image.shape)

image = image.astype('float')

# process
image = image.mean(axis=2)

image = image.astype(dtype=np.uint8)
cv2.imwrite('result.png', image)



(801, 1601, 3)


True

In [ ]:
import cv2
import numpy as np

image = cv2.imread('FakeBackground.png', 1)
print(image.shape)

image = image.astype('float')

# process
vector = np.array([1/3, 1/3, 1/3])      # lấy trung bình của 3 kênh màu
image = image@vector

image = image.astype(dtype=np.uint8)
cv2.imwrite('result2.png', image)



(801, 1601, 3)


True

In [7]:
import numpy as np

data = np.array([2, 8, 4, 9])

result = np.where(data%2 == 0, 5, 9)
print(result)

[5 5 5 9]


In [13]:
import numpy as np

data = np.array([20, 180, 4, 70], dtype=np.uint8)

_, result = cv2.threshold(data, 100, 255, cv2.THRESH_BINARY)
print(result)

result[result == 0] = 1
print(result)

[[  0 255   0   0]]
[[  1 255   1   1]]


In [ ]:
import numpy as np
import cv2

bg = cv2.imread('FakeBackground.png', 1)
bg = cv2.resize(bg, (640, 480))

img = cv2.imread('StillImage.png', 1)
img = cv2.resize(img, (640, 480))

difference = cv2.absdiff(bg,img)